app = "mood-intel-frontend"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    VITE_POCKETBASE_URL = "https://mood-intel-backend.fly.dev"

[env]
  PORT = "80"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
